#! /usr/bin/env python

import webbrowser

yes=["jeyeeah","yes", "yeah", "ya", "sure", "sure do", "ya", "you betcha", "y", "yeppers", "yep", "yup", "why not", "ok", "okay", "yessm", "otay", "mmhmm","good","fine","thatll do pig", "definiely","totally", "absolutely","go", "go for it", "will", "lets", "alright","all right", "aight","great","wonderful","amazing","awesome"]
no=["no", "nope", "nopers", "off", "good bye", "go away", "nah", "bye", "naw", "n","nothin","none","im good","better not","na","n/a","definitely not","not", "absolutely not", "dont", "wont", "lets not"]

def inquire(question,result_False,ans_True,ans_False):
    n=0.0
    while True:
        x=input("\n%s"%(question))
        x=x.replace(",","")
        x=x.replace("'","")
        x=x.replace("?","")
        x=x.replace("!","")
        x=x.replace(".","")
        x=x.replace(";","")
        x=x.replace(":","")
        x=x.strip()
        x=x.lower()

        # Match the entire phrase to the items in the answer list.

        if x in ans_True:
            n+=3
        if x in ans_False:
            n+=-3

        # Score the phrase based on the words in it which match those in the answer lists,
        # favoring the words that come first.
        
        word=len(x.split(" "))+1
        for i in x.split(" "):
            if i in ans_True:
                n+=word
            if i in ans_False:
                n+=word*(-1)
            word+=-1


        #Score the fragments of the phrase that match items in the list.
            
        if len(x)>1:
            for li in ans_True:
                if len(li)>2 and li in x:
                    n+=.2
            for li in ans_False:
                if len(li)>2 and li in x:
                    n+=-.2
        if n>0:
            return(True)
        if n<0:
            print(result_False)
            return(False)
                
        print("What?? Yes or no? ")
        continue

def replaceHyphensForASCII(s):
    s=s.replace("\u2010","\u002D") # Replace different dashes with hyphens
    s=s.replace("\u2011","\u002D") # which can be converted to ASCII
    s=s.replace("\u2012","\u002D")
    s=s.replace("\u2013","\u002D")
    s=s.replace("\u2014","\u002D\u002D")
    s=s.replace("\u2015","\u002D")

email=input("Paste Sue's email here: ").replace("pm","p.m.")
email=email.replace("am","a.m.")
replaceHyphensForASCII(email)

with open ("New_Dixon_Schedule.ics", 'w') as ics:
    ics.write("BEGIN:VCALENDAR\n")
    for line in email.split("\n"):
        if line.strip() == "":
            continue
        else:
            i=0
            # Parse out all of the dates
            eventdate=[]
            date=((line.split("/"))[:3])
            for number in date:
                i+=1
                if i==3:
                    number=number[:2]
                else:
                    number=number[-2:]
                eventdate+=[number.strip()]
            month,day,year = eventdate
            month=month.zfill(2)
            day=day.zfill(2)
            year=year.zfill(2)
            datestamp=("20%s%s%s"%(year,month,day))
            print("Date=",datestamp)

            # Parse out all of the times
            time=("0"+(line.split(":"))[0])[-2:].split()
            time+=((line.split(":"))[1])[:2]+"00"
            time=int("".join(time).strip())
            if "p.m." in line.lower():
                time+=120000
            outtime=sorted([time+40000,235900])[0]
            print("Time=",time)
            print("Outtime=",outtime)
            DTSTART = datestamp+"T"+str(time)
            DTEND = datestamp+"T"+str(outtime)

            # Parse out name of event
            l=[]
            for item in line.split("     "):
                if len(item.strip())>0:
                    if (item.strip()[0]).isalpha()==True:
                        item=item.replace(".","")
                        l+=[item.strip()]
            
            SUMMARY=((l[-1]).strip())
     #       SUMMARY = (line.split(".")[-1]).strip()
            print("Name=",SUMMARY)

            print("\n")

            ics.write("BEGIN:VEVENT\nDTEND;TZID=America/Los_Angeles:%s\nLOCATION:Work\\n600 E A St\\nDixon CA 95620\nSUMMARY:%s\nDTSTART;TZID=America/Los_Angeles:%s\nX-APPLE-STRUCTURED-LOCATION;VALUE=URI;X-ADDRESS=600 E A St\\\\nDixon CA 95\n 620;X-APPLE-RADIUS=111;X-TITLE=Work:geo:38.444420,-121.816116\nEND:VEVENT\n"%(DTEND,SUMMARY,DTSTART))
    ics.write("END:VCALENDAR")
    print("Your new schedule for the month has been saved as 'New_Dixon_Schedule.ics'")

if inquire("Does this look good? ","Oh. Better luck next time :/",yes, no)==True:
    print("Opening Calendar app...")
    webbrowser.open('file:///Users/Adam/Desktop/Stuff/Programs/New_Dixon_Schedule.ics')    
